export * from './event'
export * from './eventstore'
export * from './cqrs-es.module'
export * from './aggregate.repository'
export * from './decorators/inject-repository.decorator'
export * from './contract/config'
export * from './contract/constant'
export * from './interfaces/options.interface'
export * from './aggregate-root'
export * from './utils/test-aggregate.repository'

export { expectedVersion as ExpectedVersion } from 'node-eventstore-client'
